[package]
name = "aocrs"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
enum-iterator = "1.4.1"
glam = "0.24.2"
nom = "7.1.3"
num = "0.4.1"
regex = { version = "1.10.2" }
