[package]
name = "aocrs"
version = "0.1.0"
edition = "2021"

[toolchain]
channel = "nightly"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
regex = { version = "1.10.2" }
